### ISSUE TITLE
pyzmq url not found

### ISSUE THREAD

**Issue by pelson** [conda-forge/pyzmq-feedstock#29]
_From @nick-youngblut on February 14, 2018 9:46_

I'm trying to clone a repository that contains `pyzmq`, and I'm continually getting the following error:

```
$ conda create --clone py3 -n py3_genome
Source:      /ebio/abt3_projects/software/miniconda3/envs/py3
Destination: /ebio/abt3_projects/software/miniconda3/envs/py3_genome
Packages: 126
Files: 37

CondaError: CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/conda-forge/linux-64/pyzmq-16.0.2-py36_0.tar.bz2>
Elapsed: 00:00.534050
CF-RAY: 3ecf113daf8464db-FRA

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaError: CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/conda-forge/linux-64/pyzmq-16.0.2-py36_0.tar.bz2>
Elapsed: 00:00.549631
CF-RAY: 3ecf1140fc3b64b7-FRA

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaError: CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/conda-forge/linux-64/pyzmq-16.0.2-py36_0.tar.bz2>
Elapsed: 00:00.484043
CF-RAY: 3ecf11446ce764db-FRA

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
```

I've tried for ~1 day now with no success, so the "simple retry will get you on your way" advice doesn't seem to be working. 

Is the url broken? Do I have to update `pyzmq` in my "Source" repository in order to clone it?

```
$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.29
       conda is private : False
      conda-env version : 4.3.29
    conda-build version : not installed
         python version : 3.6.3.final.0
       requests version : 2.13.0
       root environment : /ebio/abt3_projects/software/miniconda3  (writable)
    default environment : /ebio/abt3_projects/software/miniconda3
       envs directories : /ebio/abt3_projects/software/miniconda3/envs
                          /ebio/abt3/nyoungblut/.conda/envs
          package cache : /ebio/abt3_projects/software/miniconda3/pkgs
                          /ebio/abt3/nyoungblut/.conda/pkgs
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://conda.anaconda.org/qiime2/linux-64
                          https://conda.anaconda.org/qiime2/noarch
            config file : /ebio/abt3/nyoungblut/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.29 requests/2.13.0 CPython/3.6.3 Linux/4.4.67 debian/stretch/sid glibc/2.23
                UID:GID : 6354:350
```

_Copied from original issue: conda-forge/conda-forge.github.io#528_

**Comment by pelson** [comment]
Thanks for asking @nick-youngblut. Has a pyzmq binary been removed in the last 12 hrs @conda-forge/pyzmq?

**Comment by SylvainCorlay** [comment]
Not that I know.

**Comment by jakirkham** [comment]
Is it referring to a package that has since been marked broken? Also could you please include channels? Didn’t see them above.

**Comment by minrk** [comment]
They haven't been removed, but some builds of pyzmq have been [marked as broken](https://anaconda.org/conda-forge/pyzmq/files?version=16.0.2) as a result of the issues discussed in #25. I thought this happened weeks ago, though. The builds that should have been marked as broken are only those that depended on zeromq '4.2.*' (16.0.2 builds 1 and 2 on linux and mac). The listed example (16.0.2 build 0) depends on zeromq-4.1 though, and I don't think it should have any issues, so perhaps it was marked as broken by mistake. If we had access to metadata updates, this would be preferable to marking packages with insufficient dependency pinning as entirely broken.

We've encountered issues like this on Binder, where marking a package as broken has caused frozen environments to be not installable anymore. As a result, we [include the conda-forge/label/broken](https://github.com/jupyter/repo2docker/blob/master/repo2docker/buildpacks/conda/environment.frozen.yml#L7) channel as a lowest priority in our channels when installing a frozen env, so that any package we froze that was marked broken will still be installable.

What I really wish were the behavior for broken packages was "Don't install this unless this build has been requested specifically", rather than requiring the addition of another channel.

**Comment by pelson** [comment]
Thanks all.

Hope that helps @nick-youngblut.

**Comment by jakirkham** [comment]
It’s true 16.0.2 build 0 is not marked broken.

Maybe we should keep this open @pelson. I don’t think we have fixed this yet.

**Comment by isuruf** [comment]
I think https://github.com/ContinuumIO/anaconda-issues/issues is the best place to raise this issue

**Comment by nick-youngblut** [comment]
from @jakirkham:  

>  I don’t think we have fixed this yet.

Yeah, as of two minutes ago, I'm still having the same issue with `pyzmq`:

```
CondaError: CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/conda-forge/linux-64/pyzmq-16.0.2-py36_0.tar.bz2>
Elapsed: 00:00.529403
CF-RAY: 3ed7fc3f3c9964b7-FRA

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaError: CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/conda-forge/linux-64/pyzmq-16.0.2-py36_0.tar.bz2>
Elapsed: 00:00.548410
CF-RAY: 3ed7fc427f3b2336-FRA

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaError: CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/conda-forge/linux-64/pyzmq-16.0.2-py36_0.tar.bz2>
Elapsed: 00:00.479733
CF-RAY: 3ed7fc45ea2664f3-FRA

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
```

**Comment by jakirkham** [comment]
Are you able to rule out this isn’t some kind of connectivity issue? If not, it would be best to follow up with the Anaconda team.

**Comment by nick-youngblut** [comment]
Connectivity in every other basic task (eg., `conda search` or `wget`) works just fine, so I guess that I'll have to talk to the Anaconda team

**Comment by minrk** [comment]
16.0.2 build 0 *is* marked as broken on Linux and OS X (not Windows). Since they link libzmq-4.1, they could be marked unbroken, as they should not be affected by #25.

**Comment by jakirkham** [comment]
Last time I checked they were not marked broken. Seems to be the case now as well. A more accurate statement would be some, but not all builds from that version and build number were marked broken. Should we mark them all as broken?

**Comment by minrk** [comment]
All packages for [16.0.2](https://anaconda.org/conda-forge/pyzmq/files?version=16.0.2) build 0 are still marked as broken for osx and linux:

<img width="990" alt="screen shot 2018-03-01 at 20 56 18" src="https://user-images.githubusercontent.com/151929/36866628-168a50b0-1d93-11e8-9caa-593b071d7a03.png">

build 0 is not broken, so it could be unmarked. Only builds 1 and 2 have the problem that caused them to be marked broken.

**Comment by jakirkham** [comment]
Ah. Maybe that is the confusion. Was looking at Windows.

Build 0 is pinned to zmq 4.1, which wasn't using CMake on Unix builds. CMake was not used on Unix until 4.2.1 with PR ( https://github.com/conda-forge/zeromq-feedstock/pull/14 ). So think you are right that we can move the build 0 packages back.

**Comment by ocefpaf** [comment]
Closing this as stale.
